version: '3'
services:
  app:
    build:
      context: ../filesystem-api
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=filesystem_dev
